---
- name: Deploy To-Do List Container
  hosts: webservers # This targets the group from our inventory file
  become: false     # We don't need 'sudo' because Docker runs as our user

  vars:
    docker_hub_user: "shubhamsharma1975"
    image_name: "{{ docker_hub_user }}/devops-todo-automation:latest"
    container_name: "todo-api"

  tasks:
    # --- WE HAVE REMOVED THE LOGIN TASK ---
    # Ansible will now use your Mac's existing Docker login.

    - name: Stop and remove existing 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes # Don't fail if the container isn't running

    - name: Pull the 'latest' image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start the new 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        pull: false # We already pulled the image
        ports:
          - "8080:8080"