---
- name: Deploy To-Do List Container
  hosts: webservers # This targets the group from our inventory file
  become: false     # We don't need 'sudo' because Docker runs as our user

  vars:
    docker_hub_user: "shubhamsharma1975"
    image_name: "{{ docker_hub_user }}/devops-todo-automation:latest"
    container_name: "todo-api"
    # PASTE YOUR NEWEST DOCKER HUB ACCESS TOKEN (PAT) HERE
    docker_hub_token: "{{ vault_docker_hub_token }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_hub_user }}"
        password: "{{ docker_hub_token }}"

    - name: Stop and remove existing 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes # Don't fail if the container isn't running

    - name: Pull the 'latest' image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start the new 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        pull: false # We already pulled the image
        ports:
          - "8080:8080"