---
- name: Deploy To-Do List Container
  hosts: webservers # This targets the 'webservers' group in inventory.ini
  become: false     # We don't need 'sudo' for Docker Desktop

  vars:
    # This variable will be loaded from your vault.yml file
    docker_hub_user: "{{ vault_docker_hub_user }}"
    image_name: "{{ docker_hub_user }}/devops-todo-automation:latest"
    container_name: "todo-api"
    # This variable will also be loaded from your vault.yml file
    docker_hub_token: "{{ vault_docker_hub_token }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_hub_user }}"
        password: "{{ docker_hub_token }}"

    - name: Stop and remove existing 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes # Don't fail if the container isn't running

    - name: Pull the 'latest' image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start the new 'todo-api' container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        pull: false # We just pulled the image, no need to pull again
        ports:
          - "8080:8080" # Map host port 8080 to container port 8080